<?php
$settings[] =  array(
                'id' => 'social_media',
                'title' => esc_html__('SOCIAL MEDIA', 'themo'),
                'sections' => array(
                    array(
                        'id' => 'social_media_profiles',
                        'title' => esc_html__('SOCIAL MEDIA PROFILES', 'themo'),
                        'controls' => array(
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][social_media_info]',
                                'type' => 'info',
                                'label' => esc_html__('INFO:', 'themo'),
                                'default' => '',
                                'description' => __('In this section you can add links to your social profiles, to then add them to the header.', 'themo'),
                                'transport' => 'refresh',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][behance]',
                                'type' => 'text',
                                'label' => esc_html__('BEHANCE', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.behance'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][dribbble]',
                                'type' => 'text',
                                'label' => esc_html__('DRIBBBLE', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.dribbble'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][facebook]',
                                'type' => 'text',
                                'label' => esc_html__('FACEBOOK', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.facebook'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][flickr]',
                                'type' => 'text',
                                'label' => esc_html__('FLICKR', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.flickr'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][google]',
                                'type' => 'text',
                                'label' => esc_html__('GOOGLE+', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.google'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][instagram]',
                                'type' => 'text',
                                'label' => esc_html__('ISTAGRAM', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.istagram'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][linkedin]',
                                'type' => 'text',
                                'label' => esc_html__('LINKED IN', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.linkedin'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][pinterest]',
                                'type' => 'text',
                                'label' => esc_html__('PINTEREST', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.pinterest'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][reddit]',
                                'type' => 'text',
                                'label' => esc_html__('REDDIT', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.reddit'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][skype]',
                                'type' => 'text',
                                'label' => esc_html__('SKYPE', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.skype'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][soundcloud]',
                                'type' => 'text',
                                'label' => esc_html__('SOUNDCLOUD', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.soundcloud'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][tumblr]',
                                'type' => 'text',
                                'label' => esc_html__('TUMBLR', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.tumblr'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][twitter]',
                                'type' => 'text',
                                'label' => esc_html__('TWITTER', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.twitter'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][vimeo]',
                                'type' => 'text',
                                'label' => esc_html__('VIMEO', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.vimeo'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][vk]',
                                'type' => 'text',
                                'label' => esc_html__('VK', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.vk'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][xing]',
                                'type' => 'text',
                                'label' => esc_html__('XING', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.xing'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                            array(
                                'id' => 'ideo_theme_options[social_media][social_media_profiles][youtube]',
                                'type' => 'text',
                                'label' => esc_html__('YOUTUBE', 'themo'),
                                'default' => ideothemo_get_themo_default_value('social_media.social_media_profiles.youtube'),
                                'description' => __('Enter your profile URL here.', 'themo'),
                                'transport' => 'postMessage',
                            ),
                        ),
                    ),
                ),
            );